Wip
jeathli/Project-1 pull request #10
Opened 2017-04-24 08:09 UTC by wozane

@yakato
 Desktop version ready for review

2017-04-24 11:15 UTC, yakato requested changes
A few changes and styles improvements:
- please rename Rebased-html.html to index.html
- write commit messages more carefully (a lot of typos)
- please replace unevenly cut images by those from https://github.com/rebased/rebased.github.com/tree/master/images
- width of page content should be the same everywhere - fit header to the rest of it
- you can add proper fonts, i.e. from here https://fonts.google.com/specimen/Montserrat, the simpliest way is to add them in head of html as `<link>` and then use as: 
```font-family: 'Montserrat';
font-weight: 400;
```
- projects section seems to be narrower than rest of site - make sure that it's 100% width of the section.
- open source section - try to vertical align center figcaption
- it would be nice if you add proper links to the main nav menu (to ids or pages)

Please see also all comments in the code.

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +  display: inline;
I am not sure about using here `display: inline` as default for all `li` tags.

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +/*-- header seciton --*/
Here and in some other places you have typos, please be more carefully.

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
>  }
Please be consistent with indents.

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +  width: 52rem;
I can suggest to change this into auto calculated padding instead of margin and width.  What if you'll need background of section? You cannot add it if there is limited width. For example: `padding: 0 calc((100% - 52rem)/2);` and here how to use calc: https://css-tricks.com/a-couple-of-use-cases-for-calc/. Also it'll help you to resize on mobiles.

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +body > header {
Width of page content should be the same everywhere - fit header to the rest of it. Also header is too short.

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +
Why do you need empty block here?

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +  font-weight: bolder;
`font-weight: bolder;` is not really a vgood practice, please rethink this when changing fonts. Also header for this section is too big and does not match design.

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +  border-bottom-left-radius: 1rem;
You can simply replace it by `border-radius: 1rem;` But I think it should be less than 1rem by the way. Also to match design - maybe change color of the border?

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +  height: 2rem;
If this one has similar styles to `contact-box`, you can declare them both in one block

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +  list-style-type: none;
You don't need here `list-style-type: none;` until it's declared at the top.

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +  flex-flow: wrap;
`flex-flow` it's shorter version of `flex-wrap` and `flex-direction`. If you need to change only one of them - there is no need to use shorthand.

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +  width: 52rem;
The same declaration as for other sections - can you move to one place?

2017-04-24 11:15 UTC, yakato commented on stylesheet.css
> +  flex-wrap: wrap;
For example here you can use shorthand for flex attributes.

2017-04-24 12:55 UTC, wozane commented on stylesheet.css
> +  display: inline;
This has been removed.

2017-04-24 12:56 UTC, wozane commented on stylesheet.css
> +/*-- header seciton --*/
Typos have been corrected.

2017-04-24 12:57 UTC, wozane commented on stylesheet.css
> +
It has been removed.

2017-04-24 13:57 UTC, wozane commented on stylesheet.css
> +  width: 52rem;
It has been moved.

2017-04-24 13:58 UTC, wozane commented on stylesheet.css
> +  flex-wrap: wrap;
This has been changed.

2017-04-24 14:02 UTC, wozane commented
@yakato please review my changes.

2017-04-25 13:44 UTC, wozane commented
@yakato 
Request for further code review.

2017-04-25 14:06 UTC, yakato approved these changes

2017-04-25 14:33 UTC, yakato requested changes
A few more changes:
- Review using fonts (where should be Roboto/Montserrat)
- Form width (check again styles for form to match design: borders, margins, alignment)
- I think the main background image should be a little lower, when header is on fixed position, because it's hidden by it.
- #Team section : 
	- Something wrong with z-index in #team section (it's higher than fixed header). Check what happens on scrolling. 
	- Also name/nick of member should be visible on photo before hover. 
	- Something weird is happening when hover on github/twitter icon. 
	- Text of team member description is missing on hover
	- Please carefully check if overlay is always invisible - I can see that (for example on Sarniak's pic) it's under the figure and overflows Projects header
- In #open-source section please adapt proper size of technology images and alignment of member's photos. Also something is wrong with line under the Travis CI
- Rest of visual improvements can be moved to final review after responsive versions

2017-04-25 14:33 UTC, yakato commented on stylesheet.css
> +  font-size: 1.2rem
Missing semicolon here

2017-04-25 14:33 UTC, yakato commented on stylesheet.css
> +.sum_up-slogan {
I don't like mixed `_` and `-` in class names. It's not mistake, it's about convention. If you're using everywhere dashes - be consitent in this project (there is no need here to use this mixing syntax)

2017-04-26 13:28 UTC, wozane commented
@yakato 
please check changes

2017-04-27 16:05 UTC, yakato approved these changes

2017-04-27 16:05 UTC, yakato commented
@wozane Thanks for applying most of requested changes. Rest of small improvements we're moving to final review. Please continue with responsive design.

2017-04-27 16:14 UTC, yakato commented on stylesheet.css
> +@media (min-width: 992px) {
Please read about using media queries. For safety (older browsers) is common to use:
`@media only screen and (max-width: 992px)`. And there is a difference between `max-width` and `min-width` - the second one you can use when styling mobile first and going up with width. Also there is difference with using or not using `only` and `screen` words.

2017-05-09 08:11 UTC, wozane commented
@yakato 
Mobile view ready for review.

2017-05-09 11:27 UTC, yakato reviewed
- Please replace underscores by dashed in class names
- Visual: 
	- please pay attention to spaces between sections on mobile view (they're too close)
	- map in sum-up section should have `height: auto`, current height stretches it
	- rethink spaces, lineheights in intro section, headers should be smaller, different font-weight
	- VAT-ID should be inline with the number
	- check font size for each section header (last one is too big?)
	- footer background and font size
- Code: see comments in `stylesheet.css`

2017-05-09 11:27 UTC, yakato commented on stylesheet.css
> +  line-height: 1.5rem;
`.p_linehight` This class name is invalid. It should not refer to the name of the tag or to the attribute

2017-05-09 11:27 UTC, yakato commented on stylesheet.css
> +  font-family: 'Roboto';
You don't need to overwrite `font-family` again if it's specified for the `body`, only in cases when it's different.

2017-05-09 11:27 UTC, yakato commented on stylesheet.css
> +  font-weight: bold;
Decide if you're using, for example: `font-weight: 200` or `bold`

2017-05-09 11:27 UTC, yakato commented on stylesheet.css
> +  padding: 0 0;
You can simply add `padding: 0`

2017-05-09 11:27 UTC, yakato commented on stylesheet.css
> +#sum_up_contact input.sum_up_submitbox {
It should be the same class and styles as for contact form at the top of the page. Is there any  reason why you have it twice?

2017-05-09 12:04 UTC, wozane commented on stylesheet.css
> +  line-height: 1.5rem;
This has been corrected, line-height has been applied to <p> in #intro section.

2017-05-09 12:07 UTC, wozane commented on stylesheet.css
> +#sum_up_contact input.sum_up_submitbox {
The width of the submit box is different, that is the reason I created different classes.

2017-05-09 13:09 UTC, yakato commented on stylesheet.css
> +#sum_up_contact input.sum_up_submitbox {
You can use the same class, but under different section and only in this place overwrite width

2017-05-10 14:09 UTC, wozane commented
@yakato 
Remaining styles for tablets, medium devices and large devices views ready for code review.

2017-05-10 16:00 UTC, yakato requested changes
Visual improvements to do:
Mobile:
- Main background position
- Underline “Want us to work for you”
- #intro aside submitting information font size
- Team member name on the photo
- Line with arrow to load more team members 
- Add more space between #open source header and items, then more space between items - compare with original page
- Text in community should be left align
- “Now we can work with you header is too big
- Try to match map size with the original
- Contact information: email should be coloured blue, VAT ID should be inline with number of its
- Mobile Landscape view:
    - header is too short, it’s because `height: 10vh`
    - figures in projects section are not centered and fig captions are too wide
    - Open source section landscape view - when there are two members they should be also centered
    - Contact information should be centered
Tablet:
- Left side of intro section should have padding or something 
- Add brackets to intro-text
- There should be no lines between open source items

Tablet landscape (small desktop&desktop):
- Paddings/margin for nabber should be the same as for all sections
- #projects figures and figcaptions needs better alignment
- Hover effect on navbar item should be full height
- Smaller logo
- Other visual improvement which are visible when you're comparing with original page.
Rest of comments in the code.
This review is full agresive with visual part :) Now it's time to make it more perfect.

2017-05-10 16:00 UTC, yakato commented on stylesheet.css
> +  font-weight: bold;
Still looks like `bold`...

2017-05-10 16:00 UTC, yakato commented on stylesheet.css
> +  line-height: 1.5rem;
Now each `<p>` tag will have this line height. Decide if you need class for specific one or it's ok to set this line height for all of them

2017-05-10 16:00 UTC, yakato commented on stylesheet.css
> +  border-bottom-width: medium;
this one has no effect

2017-05-10 16:00 UTC, yakato commented on stylesheet.css
> +  padding: 0 0;
`padding: 0;` should be enough

2017-05-10 16:00 UTC, yakato commented on stylesheet.css
> +#sumup-contact input.sum-up-submitbox {
I am pretty sure this one looks the same on mobile as the one in intro section. You don't need separate class for it on mobile

2017-05-10 16:00 UTC, yakato commented on stylesheet.css
> +  .intro-text {
maybe it should be prefixed by #intro if `.intro-text` is inside it?

2017-05-11 09:15 UTC, wozane commented on stylesheet.css
> +  .intro-text {
This class is outside #intro. It is separate section.

2017-05-12 09:43 UTC, wozane commented on stylesheet.css
> +  border-bottom-width: medium;
It has been deleted.

2017-05-12 09:53 UTC, wozane commented on stylesheet.css
> +  padding: 0 0;
It has been corrected.

2017-05-12 11:38 UTC, wozane commented on stylesheet.css
> +#sumup-contact input.sum-up-submitbox {
It varies a bit, the class in #sumup-contact has more style attributes.

2017-05-12 17:24 UTC, yakato reviewed
- Intro section on tablet still needs space between header and form
- Figcaptions in Projects section are still not properly aligned
- Main page header needs proper padding, as the rest of sections (ladnscape tablet and wider)

Fix please this minor comments and let's move to hamburger menu. Then you can improve visual effects

2017-05-12 17:24 UTC, yakato commented on stylesheet.css
> +    line-height: 2rem;
Fix indents please, here and one up.

2017-05-12 17:24 UTC, yakato commented on stylesheet.css
> +.dropdown-content a:hover {background-color: blue;}
If you have to leave it in one line, add spaces between bracket and attr.

2017-05-12 17:24 UTC, yakato approved these changes

2017-05-15 07:55 UTC, merged